### ISSUE TITLE
使用模板生成 API

### ISSUE THREAD

**Issue by qianjunakasumi** [ishkong/go-cqhttp-docs#73]
感觉更加规范？
同时方便后面写 API 自动化更新（虽然好像更新频率也蛮低的）

```yaml
apiVersion: generator/v1
metadata:
  apiVersion: v1
  commitId: 987daad785839a9cb0425a27edc90a0a695f5c84
  creationTimestamp: '2022-03-04T04:49:41Z'
spec:
  CQSendGroupMessage:
    metadata:
      type: group
      availableVersion: v1
      annotations:
    spec:
      name:
        metadata:
          autotype: true
        spec: 发送群消息
      endpoint: /send_group_msg
      description: |-
       发送群消息
      payload:
        metadata:
          annotations:
        spec:
          - name: group_id
            type:
              metadata:
                autotype: true
                link: none
              spec: int64
            default: none
            description: none
      response:
        metadata:
            annotations:
        spec:
```

随手搓的一个示例，不是定稿
现有格式都会被考虑在内

主要目的是生成风格统一的 API 详情页面，不用考虑排版问题。需要考虑时只需要修改一个地方然后用生成器生成就可以了

感觉咋样（
